### ISSUE TITLE
[Feature Request]: Redirect to login after session timeout

### ISSUE THREAD

**Issue by golanglemonade** [theopenlane/openlane-ui#474]
### Type of Request

Feature

### What problem are you trying to solve?

We have a dialog that shows after your session times out, however, its not user friendly that if I open a new tab, with an expired session, that I have to then click "login". 

![Image](https://github.com/user-attachments/assets/829c3950-cf94-43bd-92e0-f32677072382)

### Describe the solution you’d like

It would be ideal:

- After x amount of time (lets say 1 hour) the tab would auto redirect to the login. 
- A new tab opened _anytime_ after your session is logged out auto redirects to login without having to see this page and click `Login` manually

### Additional context

You can adjust the sessions locally so you aren't waiting an hour to test but updating the `.config.yaml` on the `core` repo to have these settings:

```
sessions:
    maxAge: 60
auth:
  token:
    accessDuration:   60000000000
    refreshDuration: 120000000000
    refreshOverlap: -120000000000
```
